//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppDevi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikePhoto
    {
        public int BikePhotoId { get; set; }
        public int BikeBrandId { get; set; }
        public string BikePhotoName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BikeBrand BikeBrand { get; set; }
    }
}
